"use client";
import dynamic from"next/dynamic";import Image from"next/image";import Link from"next/link";import{useEffect,useLayoutEffect,useRef,useState}from"react";import{useRouter}from"next/navigation";import type{Locale,dictionaries}from"@/lib/i18n";import FloorPlan from"./FloorPlan";import SpatialFallback from"./SpatialFallback";import{WebGLBoundary}from"./WebGLBoundary";
const Scene=dynamic(()=>import("./Scene"),{ssr:false});type Copy=(typeof dictionaries)[Locale];type Snap={section:string;offset:number;hash:string;progress:number;scrollY:number};const KEY="forma:locale-scroll";
function persistLocale(l:string){document.cookie=`forma-locale=${l};path=/;max-age=31536000;samesite=lax`}
function capture(){const items=[...document.querySelectorAll<HTMLElement>("[data-section]")];const anchor=items.reduce((best,item)=>item.getBoundingClientRect().top<=innerHeight*.5?item:best,items[0]);const hero=document.getElementById("journey");const progress=hero?Math.max(0,Math.min(1,-hero.getBoundingClientRect().top/(hero.offsetHeight-innerHeight))):0;const data:Snap={section:anchor?.id||"journey",offset:anchor?.getBoundingClientRect().top||0,hash:location.hash,progress,scrollY};sessionStorage.setItem(KEY,JSON.stringify(data));history.scrollRestoration="manual";document.documentElement.dataset.localeSwitching="true";return data}
function restore(){const raw=sessionStorage.getItem(KEY);if(!raw)return;sessionStorage.removeItem(KEY);const data=JSON.parse(raw)as Snap;const anchor=document.getElementById(data.section),hero=document.getElementById("journey");let target=data.scrollY;if(anchor)target=scrollY+anchor.getBoundingClientRect().top-data.offset;if(data.section==="journey"&&hero)target=hero.offsetTop+data.progress*(hero.offsetHeight-innerHeight);scrollTo({top:target,behavior:"instant"});document.querySelector<HTMLElement>(`.langs [data-locale="${document.documentElement.lang}"]`)?.focus({preventScroll:true});requestAnimationFrame(()=>{if(anchor)scrollTo({top:scrollY+anchor.getBoundingClientRect().top-data.offset,behavior:"instant"});delete document.documentElement.dataset.localeSwitching;history.scrollRestoration="auto"})}
function supportsWebGL(){if(new URLSearchParams(location.search).get("webgl")==="0")return false;try{const c=document.createElement("canvas");return!!(window.WebGLRenderingContext&&(c.getContext("webgl2")||c.getContext("webgl")))}catch{return false}}
export default function Experience({locale,copy}:{locale:Locale;copy:Copy}){const router=useRouter(),hero=useRef<HTMLElement>(null);const[progress,setProgress]=useState(0),[menu,setMenu]=useState(false),[material,setMaterial]=useState(0),[atlas,setAtlas]=useState(0),[webgl,setWebgl]=useState<boolean|null>(null),[cursor,setCursor]=useState({x:-100,y:-100,label:copy.cursorExplore});
 useLayoutEffect(()=>{document.documentElement.lang=locale;restore()},[locale]);useEffect(()=>{const frame=requestAnimationFrame(()=>setWebgl(supportsWebGL()));return()=>cancelAnimationFrame(frame)},[]);useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const onScroll=()=>{if(hero.current)setProgress(reduced?1:Math.max(0,Math.min(1,-hero.current.getBoundingClientRect().top/(hero.current.offsetHeight-innerHeight))))};onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>removeEventListener("scroll",onScroll)},[]);
 const switchLocale=(next:Locale)=>{if(next===locale)return;const snap=capture();persistLocale(next);router.replace(`/${next}${location.search}${snap.hash}`,{scroll:false})};const fallback=<SpatialFallback label={copy.fallbackLabel} progress={progress}/>;
 return <><a className="skip" href="#content">{copy.skip}</a><div className="cursor" style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0)`}}>{cursor.label}</div><header><Link className="logo" href={`/${locale}`}>FORMA</Link><nav>{copy.nav.map((n,i)=><a key={n} href={["#journey","#materials","#atlas","#contact"][i]}>{n}</a>)}</nav><div className="langs">{(["ru","en","es"]as const).map(l=><button data-locale={l} onClick={()=>switchLocale(l)} className={l===locale?"active":""} key={l} aria-current={l===locale?"page":undefined}>{l}</button>)}</div><button className="menuBtn" onClick={()=>setMenu(!menu)} aria-expanded={menu}>{menu?copy.close:copy.menu}</button></header>{menu&&<div className="mobileMenu">{copy.nav.map((n,i)=><a onClick={()=>setMenu(false)} key={n} href={["#journey","#materials","#atlas","#contact"][i]}>{n}</a>)}</div>}
 <main id="content" onPointerMove={e=>setCursor({x:e.clientX+14,y:e.clientY+14,label:(e.target as HTMLElement).closest("button,a")?copy.cursorView:copy.cursorExplore})}>
 <section id="journey" data-section ref={hero} className="hero"><div className="heroSticky"><div className="scene" aria-hidden>{webgl===true?<WebGLBoundary fallback={fallback} onError={()=>setWebgl(false)}><Scene progress={progress}/></WebGLBoundary>:fallback}</div><div className="grain"/><div className="heroText"><p>{copy.heroKicker}</p><h1>{copy.heroTitle.split("\n").map(x=><span key={x}>{x}</span>)}</h1></div><div className="scrollHint">{copy.scroll}<i style={{height:`${20+progress*60}px`}}/></div><div className="timeline">{copy.stages.map((s,i)=><div className={progress>=i/3?"on":""} key={s}><b>0{i+1}</b>{s}</div>)}</div></div></section>
 <section id="manifesto" data-section className="manifest"><p className="eyebrow">{copy.manifestoLabel}</p><h2>{copy.manifesto}</h2><p className="lead">{copy.manifestoBody}</p><figure className="architecturePhoto architecturePhotoWide"><Image src="/images/forma-house.webp" alt="" width={1920} height={1080}/></figure></section><section id="sequence" data-section className="sequence">{copy.sequence.map((s,i)=><article key={s}><span>0{i+1}</span><div className={`diagram d${i}`}/><h3>{s}</h3></article>)}</section>
 <section id="materials" data-section className={`materials m${material}`} onPointerMove={e=>setMaterial(Math.min(3,Math.floor((e.clientX/innerWidth)*4)))}><div><p className="eyebrow">{copy.materialsLabel}</p><h2>{copy.layersTitle}</h2><p>{copy.layersBody}</p><figure className="architecturePhoto"><Image src="/images/forma-detail.webp" alt="" width={1600} height={1000}/></figure></div><div className="materialNames">{copy.materials.map((m,i)=><button onFocus={()=>setMaterial(i)} onClick={()=>setMaterial(i)} className={i===material?"active":""} key={m}><span>0{i+1}</span>{m}</button>)}</div></section><FloorPlan copy={copy}/>
 <section id="transformation" data-section className="transform"><div className="transformStage" style={{"--p":progress}as React.CSSProperties}><div className="oldMass"/><div className="newMass"/><span>{copy.before}</span><span>{copy.after}</span></div><h2>{copy.transformTitle}</h2></section>
 <section id="atlas" data-section className="atlas"><div><p className="eyebrow">{copy.atlasLabel}</p><h2>{copy.atlasTitle}</h2><p>{copy.atlasNote}</p></div><div className="map">{copy.atlasTypes.map((t,i)=><button style={{left:`${12+(i*19)%76}%`,top:`${18+(i*23)%64}%`}} onFocus={()=>setAtlas(i)} onClick={()=>setAtlas(i)} className={atlas===i?"active":""} key={t}><i/>{t}</button>)}<div className="mapInfo"><b>0{atlas+1}</b><h3>{copy.atlasTypes[atlas]}</h3><p>{copy.atlasDetail}<br/>{copy.atlasStatus}</p></div></div></section>
 <section id="adaptation" data-section className="adapt"><div className={`adaptiveShape a${atlas%5}`} aria-hidden/><div><p className="eyebrow">{copy.adaptLabel}</p><h2>{copy.adaptTitle}</h2><p>{copy.adaptBody}</p><div className="adaptTabs">{copy.atlasTypes.map((t,i)=><button onClick={()=>setAtlas(i)} className={atlas===i?"active":""} key={t}>{t}</button>)}</div></div></section>
 <section id="contact" data-section className="cta"><div className="ctaLines"/><h2>{copy.cta}</h2><a href="https://eolabs.ru" target="_blank" rel="noreferrer">{copy.start}<span>↗</span></a></section></main><footer><b>FORMA</b><p>{copy.disclaimer}</p><a href="https://eolabs.ru">EO LABS ↗</a></footer></>}
