"use client";
import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Locale, dictionaries } from "@/lib/i18n";
import FloorPlan from "./FloorPlan";
import SpatialFallback from "./SpatialFallback";
import { WebGLBoundary } from "./WebGLBoundary";

const Scene=dynamic(()=>import("./Scene"),{ssr:false});
type Copy=(typeof dictionaries)[Locale];
type Snap={section:string;offset:number;hash:string;progress:number;scrollY:number};
const KEY="forma:locale-scroll";
const atlasImages=["residential","cultural","hospitality","urban","interior"];

function persistLocale(locale:string){document.cookie=`forma-locale=${locale};path=/;max-age=31536000;samesite=lax`}
function capture(){const items=[...document.querySelectorAll<HTMLElement>("[data-section]")];const anchor=items.reduce((best,item)=>item.getBoundingClientRect().top<=innerHeight*.5?item:best,items[0]);const hero=document.getElementById("journey");const progress=hero?Math.max(0,Math.min(1,-hero.getBoundingClientRect().top/(hero.offsetHeight-innerHeight))):0;const data:Snap={section:anchor?.id||"journey",offset:anchor?.getBoundingClientRect().top||0,hash:location.hash,progress,scrollY};sessionStorage.setItem(KEY,JSON.stringify(data));history.scrollRestoration="manual";document.documentElement.dataset.localeSwitching="true";return data}
function restore(){const raw=sessionStorage.getItem(KEY);if(!raw)return;sessionStorage.removeItem(KEY);const data=JSON.parse(raw) as Snap;const anchor=document.getElementById(data.section),hero=document.getElementById("journey");let target=data.scrollY;if(anchor)target=scrollY+anchor.getBoundingClientRect().top-data.offset;if(data.section==="journey"&&hero)target=hero.offsetTop+data.progress*(hero.offsetHeight-innerHeight);scrollTo({top:target,behavior:"instant"});document.querySelector<HTMLElement>(`.langs [data-locale="${document.documentElement.lang}"]`)?.focus({preventScroll:true});requestAnimationFrame(()=>{if(anchor)scrollTo({top:scrollY+anchor.getBoundingClientRect().top-data.offset,behavior:"instant"});delete document.documentElement.dataset.localeSwitching;history.scrollRestoration="auto"})}
function supportsWebGL(){if(new URLSearchParams(location.search).get("webgl")==="0")return false;try{const canvas=document.createElement("canvas");return!!(window.WebGLRenderingContext&&(canvas.getContext("webgl2")||canvas.getContext("webgl")))}catch{return false}}
function StageDiagram({stage,tech,rooms}:{stage:number;tech:string;rooms:readonly string[]}){return <svg className={`stageDrawing stage${stage}`} viewBox="0 0 520 380" aria-hidden="true">
 <defs><linearGradient id={`stageGlass${stage}`} x1="0" x2="1"><stop stopColor="#bed7df" stopOpacity=".82"/><stop offset="1" stopColor="#46636d" stopOpacity=".84"/></linearGradient><linearGradient id={`stageWarm${stage}`} x1="0" x2="0" y1="0" y2="1"><stop stopColor="#ffc06f"/><stop offset="1" stopColor="#94582f"/></linearGradient></defs>
 {stage===0&&<><g className="stageGrid"><path d="M54 48v270M272 48v270M460 48v270M28 78h458M28 252h458"/><circle cx="54" cy="78" r="4"/><circle cx="272" cy="78" r="4"/><circle cx="460" cy="78" r="4"/></g><g className="stagePlan"><path d="M54 78H460V252H54ZM54 252V326H460V252"/><path d="M272 78v62m0 48v64M382 78v55m0 49v70"/><path className="planOpening" d="M88 252h132m22 0h100M76 78h96M460 98v54"/><path d="M272 140h-43v46M229 140a43 43 0 0 0 43 43M382 133h-39v45M343 133a39 39 0 0 1 39 39M460 183h-42v45M418 183a42 42 0 0 1 42 42"/><rect x="305" y="96" width="60" height="82"/><path d="M313 104h44m-44 10h44m-44 10h44m-44 10h44m-44 10h44m-44 10h44m-22-50v50"/><path className="terraceLines" d="M80 278h125m22 0h125M80 290h125m22 0h125M80 302h125m22 0h125"/></g><g className="stageDimensions"><path d="M54 344v10M460 344v10M54 350h406M40 78H25M40 252H25M31 78v174"/><text x="225" y="347">12 000</text><text x="18" y="183" transform="rotate(-90 18 183)">7 200</text></g><g className="stageRoomLabels"><text x="112" y="170">{rooms[0]}</text><text x="287" y="218">{rooms[1]}</text><text x="307" y="91">{rooms[2]}</text><text x="216" y="321">{rooms[3]}</text></g></>}
 {stage===1&&<><g className="stageStructure"><path className="foundation" d="M58 298 326 354 466 306 196 251z"/><path className="slab" d="M58 244 326 299 466 251 196 197zM58 142 326 197 466 149 196 95z"/><path className="columns" d="M58 142v156M126 156v156M196 95v156M260 108v156M326 197v157M396 173v157M466 149v157"/><path className="beams" d="M58 142 326 197 466 149 196 95zM58 244 326 299 466 251 196 197z"/><path className="stageCore" d="m296 119 67 14v151l-67-14zM296 119l48-17 67 14-48 17M363 133v151l48-17V116"/><path className="stageStair" d="m303 260 64-22m-64 9 64-22m-64 9 64-22m-64 9 64-22m-64 9 64-22"/></g><g className="structureGrid"><path d="M30 326 326 388M110 298l296 62M190 270l296 62M58 142 354 204M196 95l296 62"/></g></>}
 {stage===2&&<><g className="stageBuilt"><path className="concrete" d="M58 298 326 354 466 306 452 294 327 334 70 282zM58 142 326 197 466 149 452 132 326 174 72 123zM58 244 326 299 466 251 455 236 326 278 69 226z"/><path className="glass" fill={`url(#stageGlass${stage})`} d="M70 143 326 196v81L70 225zM326 196l128-43v82l-128 42zM70 245l256 53v35L70 281z"/><path className="wood" fill={`url(#stageWarm${stage})`} d="m370 181 75-25v78l-75 25z"/><path className="core" d="m296 119 67 14v151l-67-14zM363 133l48-17v151l-48 17z"/><path className="mullions" d="M112 152v82M155 161v82M198 170v82M241 179v82M284 188v82M353 187v81M390 174v81M426 162v81"/><path className="light" d="m82 163 204 42v46L82 215z"/><path className="entry" d="m372 205 34-11v50l-34 11z"/><path className="roofLine" d="M58 142 326 197 466 149 196 95z"/></g><g className="builtDetails"><circle cx="390" cy="226" r="2"/><path d="M84 273h226M92 280h226"/></g></>}
 <g className="stageDatum"><path d="M40 365H480"/><text x="260" y="361" textAnchor="middle">{tech}</text></g>
 </svg>}

export default function Experience({locale,copy}:{locale:Locale;copy:Copy}){
 const router=useRouter(),hero=useRef<HTMLElement>(null),manifest=useRef<HTMLElement>(null),sequence=useRef<HTMLElement>(null);
 const [progress,setProgress]=useState(0),[menu,setMenu]=useState(false),[material,setMaterial]=useState(0),[atlas,setAtlas]=useState(0),[webgl,setWebgl]=useState<boolean|null>(null);
 const [cursorReady,setCursorReady]=useState(false);
 const [cursor,setCursor]=useState({x:-100,y:-100,active:false,visible:false,label:copy.cursorView,left:false});
 useLayoutEffect(()=>{document.documentElement.lang=locale;restore()},[locale]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{setWebgl(supportsWebGL());const params=new URLSearchParams(location.search),audit=params.get("audit"),auditWidth=params.get("width");if(audit){document.documentElement.dataset.audit="true";if(auditWidth){document.documentElement.style.width=`${auditWidth}px`;document.documentElement.style.maxWidth=`${auditWidth}px`;document.body.style.width=`${auditWidth}px`;document.body.style.maxWidth=`${auditWidth}px`}document.getElementById(audit)?.classList.add("auditTarget")}});return()=>cancelAnimationFrame(frame)},[]);
 useEffect(()=>{const fine=matchMedia("(pointer: fine) and (hover: hover)"),reduced=matchMedia("(prefers-reduced-motion: reduce)");let frame=0;const disable=()=>{cancelAnimationFrame(frame);delete document.documentElement.dataset.customCursor;setCursorReady(false);setCursor(value=>({...value,visible:false,active:false}))};const enable=()=>{disable();if(!fine.matches||reduced.matches||document.hidden||new URLSearchParams(location.search).get("cursor")==="system")return;frame=requestAnimationFrame(()=>{try{setCursorReady(true);if(new URLSearchParams(location.search).get("cursor-shot")==="1"){setCursor({x:innerWidth*.62,y:innerHeight*.48,active:true,visible:true,label:copy.cursorView,left:false});frame=requestAnimationFrame(()=>{document.documentElement.dataset.customCursor="ready"})}}catch{disable()}})};const visibility=()=>document.hidden?disable():enable();fine.addEventListener("change",enable);reduced.addEventListener("change",enable);addEventListener("focus",enable);addEventListener("blur",disable);document.addEventListener("visibilitychange",visibility);enable();return()=>{fine.removeEventListener("change",enable);reduced.removeEventListener("change",enable);removeEventListener("focus",enable);removeEventListener("blur",disable);document.removeEventListener("visibilitychange",visibility);disable()}},[copy.cursorView]);
 useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle("isVisible",entry.isIntersecting)),{threshold:.18});document.querySelectorAll("[data-reveal]").forEach(element=>reveal.observe(element));const onScroll=()=>{if(hero.current)setProgress(reduced?1:Math.max(0,Math.min(1,-hero.current.getBoundingClientRect().top/(hero.current.offsetHeight-innerHeight))));if(sequence.current){const rect=sequence.current.getBoundingClientRect(),p=reduced?1:Math.max(0,Math.min(1,(innerHeight*.72-rect.top)/(rect.height+innerHeight*.2)));sequence.current.style.setProperty("--sequence-progress",String(p))}if(manifest.current&&!reduced){const rect=manifest.current.getBoundingClientRect(),p=Math.max(-1,Math.min(1,(innerHeight*.5-(rect.top+rect.height*.5))/innerHeight));manifest.current.style.setProperty("--manifest-shift",`${p*34}px`)}};onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>{reveal.disconnect();removeEventListener("scroll",onScroll)}},[]);
 const switchLocale=(next:Locale)=>{if(next===locale)return;const snap=capture();persistLocale(next);router.replace(`/${next}${location.search}${snap.hash}`,{scroll:false})};
 const fallback=<SpatialFallback label={copy.fallbackLabel} progress={progress}/>;
 const onPointerMove=(event:React.PointerEvent)=>{if(!cursorReady||event.pointerType!=="mouse")return;const interactive=(event.target as HTMLElement).closest<HTMLElement>("[data-cursor]");const left=event.clientX>innerWidth-150;setCursor({x:event.clientX,y:event.clientY,active:!!interactive,visible:true,label:interactive?.dataset.cursor||copy.cursorView,left});if(document.documentElement.dataset.customCursor!=="ready")requestAnimationFrame(()=>{document.documentElement.dataset.customCursor="ready"})};
 return <>
  <a className="skip" href="#content" onPointerMove={onPointerMove}>{copy.skip}</a>
  {cursorReady&&<><div className={`cursorDot ${cursor.active?"active":""} ${cursor.visible?"visible":""}`} style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0)`}}/><div className={`cursorTip ${cursor.active&&cursor.visible?"active":""} ${cursor.left?"left":""}`} style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0)`}}>{cursor.label}</div></>}
  <header onPointerMove={onPointerMove} className={progress>.72?"headerLight":""}><Link className="logo" href={`/${locale}`}>FORMA</Link><nav>{copy.nav.map((item,i)=><a data-cursor={copy.cursorView} key={item} href={["#journey","#materials","#atlas","#contact"][i]}>{item}</a>)}</nav><div className="langs">{(["ru","en","es"] as const).map(item=><button data-cursor={copy.cursorView} data-locale={item} onClick={()=>switchLocale(item)} className={item===locale?"active":""} key={item} aria-current={item===locale?"page":undefined}>{item}</button>)}</div><button className="menuBtn" onClick={()=>setMenu(!menu)} aria-expanded={menu}>{menu?copy.close:copy.menu}</button></header>
  {menu&&<div className="mobileMenu" onPointerMove={onPointerMove}>{copy.nav.map((item,i)=><a onClick={()=>setMenu(false)} key={item} href={["#journey","#materials","#atlas","#contact"][i]}>{item}</a>)}</div>}
  <main id="content" onPointerMove={onPointerMove} onPointerEnter={onPointerMove} onPointerLeave={()=>setCursor(value=>({...value,active:false,visible:false}))}>
   <section id="journey" data-section ref={hero} className="hero"><div className="heroSticky"><div className="scene" aria-hidden>{webgl===true?<WebGLBoundary fallback={fallback} onError={()=>setWebgl(false)}><Scene progress={progress}/></WebGLBoundary>:fallback}</div><div className="grain"/><div className="heroText"><p>{copy.heroKicker}</p><h1>{copy.heroTitle.split("\n").map(line=><span key={line}>{line}</span>)}</h1></div><div className="scrollHint">{copy.scroll}<i style={{height:`${20+progress*60}px`}}/></div><div className="timeline">{copy.stages.map((stage,i)=><div className={progress>=i/3?"on":""} key={stage}><b>0{i+1}</b>{stage}</div>)}</div></div></section>
   <section id="manifesto" data-section data-reveal ref={manifest} className="manifest"><p className="eyebrow">{copy.manifestoLabel}</p><h2>{copy.manifesto}</h2><p className="lead">{copy.manifestoBody}</p><figure className="architecturePhoto architecturePhotoWide"><Image src="/images/forma-house.webp" alt="" width={1920} height={1080}/><i/><i/></figure></section>
   <section id="sequence" ref={sequence} data-section data-reveal className="sequence"><div className="sequenceRail"/>{copy.sequence.map((item,i)=><article key={item}><span>0{i+1}</span><StageDiagram stage={i} tech={copy.sequenceTech[i]} rooms={copy.sequenceRooms}/><div className="sequenceCaption"><b>{copy.sequenceTech[i]}</b><h3>{item}</h3></div></article>)}</section>
   <section id="materials" data-section className={`materials m${material}`}><div className="materialCopy"><p className="eyebrow">{copy.materialsLabel}</p><h2>{copy.layersTitle}</h2><p>{copy.layersBody}</p><figure className="materialVisual"><Image src="/images/forma-detail.webp" alt="" width={1600} height={1000}/><span className="materialScan"/><span className="materialTexture"/></figure></div><div className="materialNames">{copy.materials.map((item,i)=><button data-cursor={copy.cursorView} onPointerEnter={()=>setMaterial(i)} onFocus={()=>setMaterial(i)} onClick={()=>setMaterial(i)} aria-pressed={i===material} className={i===material?"active":""} key={item}><span>0{i+1}</span>{item}<i/></button>)}</div></section>
   <FloorPlan copy={copy}/>
   <section id="transformation" data-section className="transform"><div className="transformStage"><div className="oldMass"/><div className="newMass"/><span>{copy.before}</span><span>{copy.after}</span></div><h2>{copy.transformTitle}</h2></section>
   <section id="atlas" data-section className="atlas"><div className="atlasIntro"><p className="eyebrow">{copy.atlasLabel}</p><h2>{copy.atlasTitle}</h2><p>{copy.atlasNote}</p></div><div className="atlasDesktop"><div className="atlasIndex">{copy.atlasTypes.map((item,i)=><button data-cursor={copy.cursorView} onPointerEnter={()=>setAtlas(i)} onFocus={()=>setAtlas(i)} onClick={()=>setAtlas(i)} className={atlas===i?"active":""} key={item}><b>0{i+1}</b><span>{item}</span><i/></button>)}</div><figure className="atlasPreview" key={atlas}><Image src={`/images/atlas/${atlasImages[atlas]}.webp`} alt="" fill sizes="(max-width: 900px) 100vw, 65vw"/><figcaption><b>0{atlas+1}</b><span>{copy.atlasTypes[atlas]}</span><small>{copy.atlasDetail}<br/>{copy.atlasStatus}</small></figcaption></figure></div><div className="atlasMobile">{copy.atlasTypes.map((item,i)=><figure key={item}><Image src={`/images/atlas/${atlasImages[i]}-sm.avif`} alt="" width={720} height={480}/><figcaption><b>0{i+1}</b><h3>{item}</h3><p>{copy.atlasDetail}<br/>{copy.atlasStatus}</p></figcaption></figure>)}</div></section>
   <section id="adaptation" data-section className={`adapt a${atlas}`}><div className="adaptiveModule" aria-hidden><i/><i/><i/><i/><span>0{atlas+1}</span></div><div><p className="eyebrow">{copy.adaptLabel}</p><h2>{copy.adaptTitle}</h2><p>{copy.adaptBody}</p><div className="adaptTabs">{copy.atlasTypes.map((item,i)=><button data-cursor={copy.cursorView} onClick={()=>setAtlas(i)} className={atlas===i?"active":""} key={item}>{item}</button>)}</div></div></section>
   <section id="contact" data-section className="cta"><div className="ctaLines"/><h2>{copy.cta}</h2><a data-cursor={copy.cursorView} href="https://eolabs.ru" target="_blank" rel="noreferrer">{copy.start}<span>↗</span></a></section>
  </main><footer onPointerMove={onPointerMove}><b>FORMA</b><p>{copy.disclaimer}</p><a href="https://eolabs.ru">EO LABS ↗</a></footer>
 </>
}
