"use client";
import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Locale, dictionaries } from "@/lib/i18n";
import FloorPlan from "./FloorPlan";
import SpatialFallback from "./SpatialFallback";
import { WebGLBoundary } from "./WebGLBoundary";

const Scene=dynamic(()=>import("./Scene"),{ssr:false});
type Copy=(typeof dictionaries)[Locale];
type Snap={section:string;offset:number;hash:string;progress:number;scrollY:number};
const KEY="forma:locale-scroll";
const atlasImages=["residential","cultural","hospitality","urban","interior"];

function persistLocale(locale:string){document.cookie=`forma-locale=${locale};path=/;max-age=31536000;samesite=lax`}
function capture(){const items=[...document.querySelectorAll<HTMLElement>("[data-section]")];const anchor=items.reduce((best,item)=>item.getBoundingClientRect().top<=innerHeight*.5?item:best,items[0]);const hero=document.getElementById("journey");const progress=hero?Math.max(0,Math.min(1,-hero.getBoundingClientRect().top/(hero.offsetHeight-innerHeight))):0;const data:Snap={section:anchor?.id||"journey",offset:anchor?.getBoundingClientRect().top||0,hash:location.hash,progress,scrollY};sessionStorage.setItem(KEY,JSON.stringify(data));history.scrollRestoration="manual";document.documentElement.dataset.localeSwitching="true";return data}
function restore(){const raw=sessionStorage.getItem(KEY);if(!raw)return;sessionStorage.removeItem(KEY);const data=JSON.parse(raw) as Snap;const anchor=document.getElementById(data.section),hero=document.getElementById("journey");let target=data.scrollY;if(anchor)target=scrollY+anchor.getBoundingClientRect().top-data.offset;if(data.section==="journey"&&hero)target=hero.offsetTop+data.progress*(hero.offsetHeight-innerHeight);scrollTo({top:target,behavior:"instant"});document.querySelector<HTMLElement>(`.langs [data-locale="${document.documentElement.lang}"]`)?.focus({preventScroll:true});requestAnimationFrame(()=>{if(anchor)scrollTo({top:scrollY+anchor.getBoundingClientRect().top-data.offset,behavior:"instant"});delete document.documentElement.dataset.localeSwitching;history.scrollRestoration="auto"})}
function supportsWebGL(){if(new URLSearchParams(location.search).get("webgl")==="0")return false;try{const canvas=document.createElement("canvas");return!!(window.WebGLRenderingContext&&(canvas.getContext("webgl2")||canvas.getContext("webgl")))}catch{return false}}
function StageDiagram({stage}:{stage:number}){return <svg className={`stageDrawing stage${stage}`} viewBox="0 0 520 360" aria-hidden="true">
 {stage===0&&<><g className="stageGrid"><path d="M78 66v246M188 66v246M300 66v246M412 66v246M42 104h436M42 224h436"/><circle cx="78" cy="104" r="5"/><circle cx="188" cy="104" r="5"/><circle cx="300" cy="104" r="5"/><circle cx="412" cy="104" r="5"/></g><g className="stagePlan"><path d="M78 104h334v120H78zM188 104v120M300 104v120M78 170h110M300 170h112M245 104v66"/><path d="M68 92v-28M422 92v-28M78 74h334M64 94H38M64 234H38M48 104v120"/></g><g className="stageTicks"><path d="m74 70 8 8m102-8 8 8m104-8 8 8m102-8 8 8M44 100l8 8m-8 112 8 8"/></g><text x="231" y="61">3 600</text><text x="22" y="171" transform="rotate(-90 22 171)">7 200</text><text x="72" y="330">A</text><text x="406" y="330">D</text></>}
 {stage===1&&<><g className="stageFrame"><path d="m74 254 122 52 260-96-122-51zM74 126l122 48 260-91-122-48zM74 126v128M196 174v132M456 83v127M334 35v124"/><path d="M118 144v128M232 161v132M378 144v130M420 98v129"/><path className="stageCore" d="m275 99 60 23v128l-60-24z"/></g><g className="stageDatum"><path d="M46 320h420M48 312v16M464 312v16"/><text x="210" y="342">STRUCTURAL GRID 01</text></g></>}
 {stage===2&&<><defs><linearGradient id="glass" x1="0" x2="1"><stop stopColor="#7898a7" stopOpacity=".78"/><stop offset="1" stopColor="#263a43" stopOpacity=".9"/></linearGradient><linearGradient id="warm" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#e7af68"/><stop offset="1" stopColor="#80502f"/></linearGradient></defs><g className="stageBuilt"><path className="concrete" d="m72 254 126 54 260-97-13-15-244 88-116-48zM74 126l124 49 260-92-15-17-243 84-112-42z"/><path className="glass" d="m89 128 111 44v111L89 239zM201 173l241-84v106l-241 87z"/><path className="wood" d="m348 122 58-20v109l-58 21z"/><path className="core" d="m276 100 59 22v128l-59-23z"/><path className="mullions" d="M126 143v112M164 158v112M237 161v108M290 143v107M347 123v106M407 102v106"/><path className="light" d="m215 187 120-42v78l-120 43z"/></g><g className="stageDatum"><path d="M46 320h420M48 312v16M464 312v16"/><text x="208" y="342">MATERIAL ASSEMBLY</text></g></>}
 </svg>}

export default function Experience({locale,copy}:{locale:Locale;copy:Copy}){
 const router=useRouter(),hero=useRef<HTMLElement>(null),manifest=useRef<HTMLElement>(null);
 const [progress,setProgress]=useState(0),[menu,setMenu]=useState(false),[material,setMaterial]=useState(0),[atlas,setAtlas]=useState(0),[webgl,setWebgl]=useState<boolean|null>(null);
 const [cursor,setCursor]=useState({x:-100,y:-100,active:false,label:copy.cursorView,left:false});
 useLayoutEffect(()=>{document.documentElement.lang=locale;restore()},[locale]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{setWebgl(supportsWebGL());const params=new URLSearchParams(location.search),audit=params.get("audit"),auditWidth=params.get("width");if(audit){document.documentElement.dataset.audit="true";if(auditWidth){document.documentElement.style.width=`${auditWidth}px`;document.documentElement.style.maxWidth=`${auditWidth}px`;document.body.style.width=`${auditWidth}px`;document.body.style.maxWidth=`${auditWidth}px`}document.getElementById(audit)?.classList.add("auditTarget")}});return()=>cancelAnimationFrame(frame)},[]);
 useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle("isVisible",entry.isIntersecting)),{threshold:.18});document.querySelectorAll("[data-reveal]").forEach(element=>reveal.observe(element));const onScroll=()=>{if(hero.current)setProgress(reduced?1:Math.max(0,Math.min(1,-hero.current.getBoundingClientRect().top/(hero.current.offsetHeight-innerHeight))));if(manifest.current&&!reduced){const rect=manifest.current.getBoundingClientRect(),p=Math.max(-1,Math.min(1,(innerHeight*.5-(rect.top+rect.height*.5))/innerHeight));manifest.current.style.setProperty("--manifest-shift",`${p*34}px`)}};onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>{reveal.disconnect();removeEventListener("scroll",onScroll)}},[]);
 const switchLocale=(next:Locale)=>{if(next===locale)return;const snap=capture();persistLocale(next);router.replace(`/${next}${location.search}${snap.hash}`,{scroll:false})};
 const fallback=<SpatialFallback label={copy.fallbackLabel} progress={progress}/>;
 const onPointerMove=(event:React.PointerEvent)=>{if(event.pointerType==="touch")return;const interactive=(event.target as HTMLElement).closest<HTMLElement>("[data-cursor]");const left=event.clientX>innerWidth-150;setCursor({x:event.clientX,y:event.clientY,active:!!interactive,label:interactive?.dataset.cursor||copy.cursorView,left})};
 return <>
  <a className="skip" href="#content">{copy.skip}</a>
  <div className={`cursorDot ${cursor.active?"active":""}`} style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0)`}}/><div className={`cursorTip ${cursor.active?"active":""} ${cursor.left?"left":""}`} style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0)`}}>{cursor.label}</div>
  <header className={progress>.72?"headerLight":""}><Link className="logo" href={`/${locale}`}>FORMA</Link><nav>{copy.nav.map((item,i)=><a data-cursor={copy.cursorView} key={item} href={["#journey","#materials","#atlas","#contact"][i]}>{item}</a>)}</nav><div className="langs">{(["ru","en","es"] as const).map(item=><button data-cursor={copy.cursorView} data-locale={item} onClick={()=>switchLocale(item)} className={item===locale?"active":""} key={item} aria-current={item===locale?"page":undefined}>{item}</button>)}</div><button className="menuBtn" onClick={()=>setMenu(!menu)} aria-expanded={menu}>{menu?copy.close:copy.menu}</button></header>
  {menu&&<div className="mobileMenu">{copy.nav.map((item,i)=><a onClick={()=>setMenu(false)} key={item} href={["#journey","#materials","#atlas","#contact"][i]}>{item}</a>)}</div>}
  <main id="content" onPointerMove={onPointerMove} onPointerLeave={()=>setCursor(value=>({...value,active:false}))}>
   <section id="journey" data-section ref={hero} className="hero"><div className="heroSticky"><div className="scene" aria-hidden>{webgl===true?<WebGLBoundary fallback={fallback} onError={()=>setWebgl(false)}><Scene progress={progress}/></WebGLBoundary>:fallback}</div><div className="grain"/><div className="heroText"><p>{copy.heroKicker}</p><h1>{copy.heroTitle.split("\n").map(line=><span key={line}>{line}</span>)}</h1></div><div className="scrollHint">{copy.scroll}<i style={{height:`${20+progress*60}px`}}/></div><div className="timeline">{copy.stages.map((stage,i)=><div className={progress>=i/3?"on":""} key={stage}><b>0{i+1}</b>{stage}</div>)}</div></div></section>
   <section id="manifesto" data-section data-reveal ref={manifest} className="manifest"><p className="eyebrow">{copy.manifestoLabel}</p><h2>{copy.manifesto}</h2><p className="lead">{copy.manifestoBody}</p><figure className="architecturePhoto architecturePhotoWide"><Image src="/images/forma-house.webp" alt="" width={1920} height={1080}/><i/><i/></figure></section>
   <section id="sequence" data-section data-reveal className="sequence"><div className="sequenceRail"/>{copy.sequence.map((item,i)=><article key={item}><span>0{i+1}</span><StageDiagram stage={i}/><h3>{item}</h3></article>)}</section>
   <section id="materials" data-section className={`materials m${material}`}><div className="materialCopy"><p className="eyebrow">{copy.materialsLabel}</p><h2>{copy.layersTitle}</h2><p>{copy.layersBody}</p><figure className="materialVisual"><Image src="/images/forma-detail.webp" alt="" width={1600} height={1000}/><span className="materialScan"/><span className="materialTexture"/></figure></div><div className="materialNames">{copy.materials.map((item,i)=><button data-cursor={copy.cursorView} onPointerEnter={()=>setMaterial(i)} onFocus={()=>setMaterial(i)} onClick={()=>setMaterial(i)} aria-pressed={i===material} className={i===material?"active":""} key={item}><span>0{i+1}</span>{item}<i/></button>)}</div></section>
   <FloorPlan copy={copy}/>
   <section id="transformation" data-section className="transform"><div className="transformStage"><div className="oldMass"/><div className="newMass"/><span>{copy.before}</span><span>{copy.after}</span></div><h2>{copy.transformTitle}</h2></section>
   <section id="atlas" data-section className="atlas"><div className="atlasIntro"><p className="eyebrow">{copy.atlasLabel}</p><h2>{copy.atlasTitle}</h2><p>{copy.atlasNote}</p></div><div className="atlasDesktop"><div className="atlasIndex">{copy.atlasTypes.map((item,i)=><button data-cursor={copy.cursorView} onPointerEnter={()=>setAtlas(i)} onFocus={()=>setAtlas(i)} onClick={()=>setAtlas(i)} className={atlas===i?"active":""} key={item}><b>0{i+1}</b><span>{item}</span><i/></button>)}</div><figure className="atlasPreview" key={atlas}><Image src={`/images/atlas/${atlasImages[atlas]}.webp`} alt="" fill sizes="(max-width: 900px) 100vw, 65vw"/><figcaption><b>0{atlas+1}</b><span>{copy.atlasTypes[atlas]}</span><small>{copy.atlasDetail}<br/>{copy.atlasStatus}</small></figcaption></figure></div><div className="atlasMobile">{copy.atlasTypes.map((item,i)=><figure key={item}><Image src={`/images/atlas/${atlasImages[i]}-sm.avif`} alt="" width={720} height={480}/><figcaption><b>0{i+1}</b><h3>{item}</h3><p>{copy.atlasDetail}<br/>{copy.atlasStatus}</p></figcaption></figure>)}</div></section>
   <section id="adaptation" data-section className={`adapt a${atlas}`}><div className="adaptiveModule" aria-hidden><i/><i/><i/><i/><span>0{atlas+1}</span></div><div><p className="eyebrow">{copy.adaptLabel}</p><h2>{copy.adaptTitle}</h2><p>{copy.adaptBody}</p><div className="adaptTabs">{copy.atlasTypes.map((item,i)=><button data-cursor={copy.cursorView} onClick={()=>setAtlas(i)} className={atlas===i?"active":""} key={item}>{item}</button>)}</div></div></section>
   <section id="contact" data-section className="cta"><div className="ctaLines"/><h2>{copy.cta}</h2><a data-cursor={copy.cursorView} href="https://eolabs.ru" target="_blank" rel="noreferrer">{copy.start}<span>↗</span></a></section>
  </main><footer><b>FORMA</b><p>{copy.disclaimer}</p><a href="https://eolabs.ru">EO LABS ↗</a></footer>
 </>
}
