export const locales = ["ru", "en", "es"] as const;
export type Locale = (typeof locales)[number];
export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);

const en = {
  skip: "Skip to content", cursorExplore: "EXPLORE", cursorView: "VIEW", nav: ["Journey", "Materials", "Atlas", "Contact"], menu: "Menu", close: "Close",
  stages: ["Sketch", "Structure", "Realization"], heroKicker: "03 / SPATIAL JOURNEY", heroTitle: "ENTER\nTHE IDEA.", scroll: "SCROLL TO BUILD",
  manifestoLabel: "01 — MANIFESTO", manifesto: "Architecture begins before matter.", manifestoBody: "FORMA is a digital study of the moment when intention becomes structure. Move through the project: from measured line to inhabited light.",
  sequence: ["A line establishes direction.", "Structure gives the line weight.", "Material makes space perceptible."], sequenceTech: ["ARCHITECTURAL PLAN", "STRUCTURAL SYSTEM", "MATERIAL ASSEMBLY"], sequenceRooms: ["LIVING", "KITCHEN", "CORE", "TERRACE"],
  materialsLabel: "04 — TACTILE INDEX", materials: ["Concrete", "Glass", "Timber", "Stone"], layersTitle: "Material layers", layersBody: "Move across the surface. Each layer changes light, density and atmosphere.",
  floorLabel: "05 — INTERACTIVE PLAN", floorTitle: "Space, read from both sides.", floorBody: "The ground floor of the same house: plan and volume use one structural grid.", floorInstruction: "Select a room on the plan — its spatial volume will appear on the right.", floorDemo: "Demonstration data",
  floorAreas: ["Living room", "Kitchen & dining", "Study", "Terrace"], floorSizes: ["48 m²", "32 m²", "27 m²", "36 m²"], floorFunctions: ["A double-aspect room opening to the terrace.", "A shared table beside the service core.", "A quiet room by the entrance.", "An outdoor extension of the living room."], floorPlan: "Ground-floor plan", floorVolume: "Selected spatial volume",
  before: "EXISTING MASS", after: "ADAPTIVE FORM", transformTitle: "One volume. Another way of living.", atlasLabel: "08 — CARTOGRAPHY", atlasTypes: ["Residential", "Cultural", "Hospitality", "Urban", "Interior"], atlasTitle: "Project atlas", atlasNote: "Conceptual studies — not built projects", atlasDetail: "Concept study · Temperate climate", atlasStatus: "Status — spatial research",
  adaptLabel: "09 — ADAPTATION", adaptTitle: "A system shaped to its context.", adaptBody: "One spatial grammar can speak for architecture practices, developers, construction teams, interior studios and modular makers.", cta: "LET’S GIVE YOUR IDEAS SPACE.", start: "Start a project", disclaimer: "FORMA is a demonstration digital concept by EO Labs. Names, objects and project data illustrate a possible user experience.", fallbackLabel: "Spatial study — static view",
};

const ru: typeof en = {
  skip: "Перейти к содержанию", cursorExplore: "ИССЛЕДОВАТЬ", cursorView: "СМОТРЕТЬ", nav: ["Путь", "Материалы", "Атлас", "Контакт"], menu: "Меню", close: "Закрыть",
  stages: ["Эскиз", "Конструкция", "Воплощение"], heroKicker: "03 / ПРОСТРАНСТВЕННЫЙ ПУТЬ", heroTitle: "ВОЙДИТЕ\nВ ИДЕЮ.", scroll: "ЛИСТАЙТЕ, ЧТОБЫ СОЗДАТЬ",
  manifestoLabel: "01 — МАНИФЕСТ", manifesto: "Архитектура начинается до материи.", manifestoBody: "FORMA — цифровое исследование момента, когда намерение становится конструкцией. Пройдите проект от размерной линии до обжитого света.",
  sequence: ["Линия задаёт направление.", "Конструкция придаёт линии вес.", "Материал делает пространство осязаемым."], sequenceTech: ["АРХИТЕКТУРНЫЙ ПЛАН", "КОНСТРУКТИВНАЯ СИСТЕМА", "МАТЕРИАЛЬНАЯ СБОРКА"], sequenceRooms: ["ГОСТИНАЯ", "КУХНЯ", "ЯДРО", "ТЕРРАСА"],
  materialsLabel: "04 — ТАКТИЛЬНЫЙ ИНДЕКС", materials: ["Бетон", "Стекло", "Дерево", "Камень"], layersTitle: "Слои материала", layersBody: "Двигайтесь по поверхности. Каждый слой меняет свет, плотность и атмосферу.",
  floorLabel: "05 — ИНТЕРАКТИВНЫЙ ПЛАН", floorTitle: "Пространство с двух точек зрения.", floorBody: "Первый этаж того же дома: план и объём построены на одной конструктивной сетке.", floorInstruction: "Выберите помещение на плане — справа появится его пространственный объём.", floorDemo: "Демонстрационные данные",
  floorAreas: ["Гостиная", "Кухня и столовая", "Кабинет", "Терраса"], floorSizes: ["48 м²", "32 м²", "27 м²", "36 м²"], floorFunctions: ["Сквозное пространство с выходом на террасу.", "Общий стол рядом с инженерным ядром.", "Тихая комната у входа.", "Открытое продолжение гостиной."], floorPlan: "План первого этажа", floorVolume: "Объём выбранного помещения",
  before: "ИСХОДНЫЙ ОБЪЁМ", after: "АДАПТИВНАЯ ФОРМА", transformTitle: "Один объём. Другой способ жить.", atlasLabel: "08 — КАРТОГРАФИЯ", atlasTypes: ["Жилая архитектура", "Культурные объекты", "Гостиничная архитектура", "Городская среда", "Интерьеры"], atlasTitle: "Атлас проектов", atlasNote: "Концептуальные исследования — не построенные объекты", atlasDetail: "Концептуальное исследование · Умеренный климат", atlasStatus: "Статус — пространственное исследование",
  adaptLabel: "09 — АДАПТАЦИЯ", adaptTitle: "Система, меняющаяся вместе с контекстом.", adaptBody: "Один пространственный язык может работать для архитектурных бюро, девелоперов, строителей, интерьерных студий и производителей модульных домов.", cta: "ДАДИМ ВАШИМ ИДЕЯМ ПРОСТРАНСТВО.", start: "Начать проект", disclaimer: "FORMA — демонстрационный цифровой концепт EO Labs. Названия, объекты и проектные данные используются для демонстрации возможного пользовательского опыта.", fallbackLabel: "Пространственное исследование — статичный вид",
};

const es: typeof en = {
  skip: "Ir al contenido", cursorExplore: "EXPLORAR", cursorView: "VER", nav: ["Recorrido", "Materiales", "Atlas", "Contacto"], menu: "Menú", close: "Cerrar",
  stages: ["Boceto", "Estructura", "Realización"], heroKicker: "03 / RECORRIDO ESPACIAL", heroTitle: "ENTRA EN\nLA IDEA.", scroll: "DESPLÁZATE PARA CONSTRUIR",
  manifestoLabel: "01 — MANIFIESTO", manifesto: "La arquitectura comienza antes que la materia.", manifestoBody: "FORMA estudia digitalmente el instante en que una intención se convierte en estructura. Recorre el proyecto: de la línea medida a la luz habitada.",
  sequence: ["Una línea establece la dirección.", "La estructura da peso a la línea.", "El material hace perceptible el espacio."], sequenceTech: ["PLANO ARQUITECTÓNICO", "SISTEMA ESTRUCTURAL", "ENSAMBLAJE MATERIAL"], sequenceRooms: ["ESTAR", "COCINA", "NÚCLEO", "TERRAZA"],
  materialsLabel: "04 — ÍNDICE TÁCTIL", materials: ["Hormigón", "Vidrio", "Madera", "Piedra"], layersTitle: "Capas materiales", layersBody: "Recorre la superficie. Cada capa transforma la luz, la densidad y la atmósfera.",
  floorLabel: "05 — PLANO INTERACTIVO", floorTitle: "El espacio, leído desde ambos lados.", floorBody: "La planta baja de la misma casa: plano y volumen comparten una única retícula estructural.", floorInstruction: "Selecciona una estancia en el plano: su volumen espacial aparecerá a la derecha.", floorDemo: "Datos demostrativos",
  floorAreas: ["Sala de estar", "Cocina y comedor", "Estudio", "Terraza"], floorSizes: ["48 m²", "32 m²", "27 m²", "36 m²"], floorFunctions: ["Un espacio pasante abierto a la terraza.", "Una mesa común junto al núcleo técnico.", "Una estancia tranquila junto al acceso.", "La prolongación exterior de la sala de estar."], floorPlan: "Plano de planta baja", floorVolume: "Volumen de la estancia seleccionada",
  before: "VOLUMEN EXISTENTE", after: "FORMA ADAPTATIVA", transformTitle: "Un volumen. Otra forma de habitar.", atlasLabel: "08 — CARTOGRAFÍA", atlasTypes: ["Residencial", "Cultural", "Hospitalidad", "Urbanismo", "Interiorismo"], atlasTitle: "Atlas de proyectos", atlasNote: "Estudios conceptuales — no son obras construidas", atlasDetail: "Estudio conceptual · Clima templado", atlasStatus: "Estado — investigación espacial",
  adaptLabel: "09 — ADAPTACIÓN", adaptTitle: "Un sistema que responde a su contexto.", adaptBody: "Un mismo lenguaje espacial puede servir a estudios de arquitectura, promotores, constructoras, interioristas y fabricantes modulares.", cta: "DEMOS ESPACIO A TUS IDEAS.", start: "Iniciar un proyecto", disclaimer: "FORMA es un concepto digital demostrativo de EO Labs. Los nombres, objetos y datos ilustran una posible experiencia de usuario.", fallbackLabel: "Estudio espacial — vista estática",
};

export const dictionaries = { en, ru, es } as const;
