export const locales = ["ru","en","es"] as const;
export type Locale = typeof locales[number];
export const isLocale = (v:string):v is Locale => locales.includes(v as Locale);

const shared = {
  stages:["Sketch","Structure","Realization"],
  materials:["Concrete","Glass","Timber","Stone"],
  atlasTypes:["Residential","Cultural","Hospitality","Urban","Interior"],
};
export const dictionaries = {
 en:{...shared,nav:["Journey","Materials","Atlas","Contact"],heroKicker:"03 / SPATIAL JOURNEY",heroTitle:"ENTER\nTHE IDEA.",scroll:"SCROLL TO BUILD",manifesto:"Architecture begins before matter.",manifestoBody:"FORMA is a digital study of the moment when intention becomes structure. Move through the project: from measured line to inhabited light.",sequence:["A line establishes direction.","Structure gives the line weight.","Material makes space perceptible."],layersTitle:"Material layers",layersBody:"Move across the surface. Each layer changes light, density and atmosphere.",before:"EXISTING MASS",after:"ADAPTIVE FORM",transformTitle:"One volume. Another way of living.",atlasTitle:"Project atlas",atlasNote:"Conceptual studies — not built projects",adaptTitle:"A system shaped to its context.",adaptBody:"One spatial grammar can speak for architecture practices, developers, construction teams, interior studios and modular makers.",cta:"LET’S GIVE YOUR IDEAS SPACE.",start:"Start a project",disclaimer:"FORMA is a demonstration digital concept by EO Labs. Names, objects and project data illustrate a possible user experience.",menu:"Menu",close:"Close"},
 ru:{...shared,nav:["Путь","Материалы","Атлас","Контакт"],heroKicker:"03 / ПРОСТРАНСТВЕННЫЙ ПУТЬ",heroTitle:"ВОЙДИТЕ\nВ ИДЕЮ.",scroll:"ЛИСТАЙТЕ, ЧТОБЫ СОЗДАТЬ",manifesto:"Архитектура начинается до материи.",manifestoBody:"FORMA — цифровое исследование момента, когда намерение становится конструкцией. Пройдите проект от размерной линии до обжитого света.",sequence:["Линия задаёт направление.","Конструкция придаёт линии вес.","Материал делает пространство осязаемым."],layersTitle:"Слои материала",layersBody:"Двигайтесь по поверхности. Каждый слой меняет свет, плотность и атмосферу.",before:"ИСХОДНЫЙ ОБЪЁМ",after:"АДАПТИВНАЯ ФОРМА",transformTitle:"Один объём. Другой способ жить.",atlasTitle:"Атлас проектов",atlasNote:"Концептуальные исследования — не построенные объекты",adaptTitle:"Система, меняющаяся вместе с контекстом.",adaptBody:"Один пространственный язык может работать для архитектурных бюро, девелоперов, строителей, интерьерных студий и производителей модульных домов.",cta:"ДАДИМ ВАШИМ ИДЕЯМ ПРОСТРАНСТВО.",start:"Начать проект",disclaimer:"FORMA — демонстрационный цифровой концепт EO Labs. Названия, объекты и проектные данные используются для демонстрации возможного пользовательского опыта.",menu:"Меню",close:"Закрыть"},
 es:{...shared,nav:["Recorrido","Materiales","Atlas","Contacto"],heroKicker:"03 / RECORRIDO ESPACIAL",heroTitle:"ENTRA EN\nLA IDEA.",scroll:"DESPLÁZATE PARA CONSTRUIR",manifesto:"La arquitectura comienza antes que la materia.",manifestoBody:"FORMA estudia digitalmente el instante en que una intención se convierte en estructura. Recorre el proyecto: de la línea medida a la luz habitada.",sequence:["Una línea establece la dirección.","La estructura da peso a la línea.","El material hace perceptible el espacio."],layersTitle:"Capas materiales",layersBody:"Recorre la superficie. Cada capa transforma la luz, la densidad y la atmósfera.",before:"VOLUMEN EXISTENTE",after:"FORMA ADAPTATIVA",transformTitle:"Un volumen. Otra forma de habitar.",atlasTitle:"Atlas de proyectos",atlasNote:"Estudios conceptuales — no son obras construidas",adaptTitle:"Un sistema que responde a su contexto.",adaptBody:"Un mismo lenguaje espacial puede servir a estudios de arquitectura, promotores, constructoras, interioristas y fabricantes modulares.",cta:"DEMOS ESPACIO A TUS IDEAS.",start:"Iniciar un proyecto",disclaimer:"FORMA es un concepto digital demostrativo de EO Labs. Los nombres, objetos y datos ilustran una posible experiencia de usuario.",menu:"Menú",close:"Cerrar"}
} as const;
